remove depends block in fmj
VulpixelMC/pride-year pull request #2
Opened 2021-07-02 00:16 UTC by wafflecoffee

It works just fine on 1.16 with zero modifications

2021-07-02 20:39 UTC, TehcJS requested changes
keep `java: >=16` and `quilt-loading-screen: 2.x`

2021-07-02 20:39 UTC, TehcJS commented on src/main/resources/fabric.mod.json
> -    "quilt-loading-screen": "2.x"
the mod depends on quilt-loading-screen 2.x, so we can remove the `minecraft` dependency. also, it does require java 16 to run :/, so we can't do much more than that.

2021-07-02 20:39 UTC, TehcJS commented on src/main/resources/fabric.mod.json
> -    "quilt-loading-screen": "2.x"
the mod depends on quilt-loading-screen 2.x, so we can remove the `minecraft` dependency. also, it does require java 16 to run :/, so we can't do much more than that.

2021-07-02 20:39 UTC, TehcJS commented on src/main/resources/fabric.mod.json
> -    "quilt-loading-screen": "2.x"
also we can remove `fabricloader >=0.11.3` since it doesn't use any fabricloader stuff

2021-07-02 21:06 UTC, wafflecoffee commented on src/main/resources/fabric.mod.json
> -    "quilt-loading-screen": "2.x"
> the mod depends on quilt-loading-screen 2.x

no it doesn't, it works fine on 1.x

> it does require java 16 to run :/

no it doesn't

2021-07-13 17:43 UTC, wafflecoffee commented
config option in upstream now so this doesn't matter anymore

2021-07-13 17:43 UTC, closed without merging